name: Sculpting Action Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: suziwen/suziwen.github.io
          ref: refs/heads/main
          path: 'public'
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      - uses: suziwen/gatsby-gh-pages-action@v2.2.10
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          deploy-repo: suziwen.github.io
